# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby_teste_a

on:
  workflow_dispatch:
  pull_request:
    branches: [ modelo ]
  schedule:
  - cron: "58 18 * * 5"
  
jobs:
  test_modelo:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7']

    steps:
    - uses: actions/checkout@v2
      with:
        ref: modelo      
    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        working-directory: /home/runner/work/treinamento-automacao/treinamento-automacao/ui
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        
 

    - uses: nanasess/setup-chromedriver@master
      with:
           # Optional: do not specify to match Chrome's version
          chromedriver-version: '95.0.4638.69'
    - run: |
         export DISPLAY=:99
         chromedriver --url-base=/wd/hub &
         sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          
    - name: Run tests
      run: |
        cd ui/
        bundle exec cucumber -t @inicio_1 chrome_headless==true
      
    - name: Upload Screenshots
      uses: actions/upload-artifact@v2.2.4
      if: failure()
      with:
        name: screenshots
        path: data/screenshots/bugs

  test_master:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7']

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master      
    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        working-directory: /home/runner/work/treinamento-automacao/treinamento-automacao/ui
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        
 

    - uses: nanasess/setup-chromedriver@master
      with:
           # Optional: do not specify to match Chrome's version
          chromedriver-version: '95.0.4638.69'
    - run: |
         export DISPLAY=:99
         chromedriver --url-base=/wd/hub &
         sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          
    - name: Run tests
      run: |
        cd ui/
        bundle exec cucumber -t @tag chrome_headless==true
      
    - name: Upload Screenshots
      uses: actions/upload-artifact@v2.2.4
      if: failure()
      with:
        name: screenshots
        path: data/screenshots/bugs
